training_arguments:
  output_dir: "./gpt2-lora-translation"
  per_device_train_batch_size: 24
  per_device_eval_batch_size: 24
  gradient_accumulation_steps: 2
  save_strategy: "epoch"
  logging_strategy: "steps"
  learning_rate: 3.0e-4
  num_train_epochs: 3
  save_steps: 300
  logging_steps: 75
  report_to: "none"
  remove_unused_columns: false
  label_smoothing_factor: 0.1
  dataloader_pin_memory: true
  dataloader_num_workers: 2
  fp16: false
  warmup_steps: 100
  weight_decay: 0.01
  max_grad_norm: 1.0
  optim: "adamw_torch"
  group_by_length: true
  label_names: ["labels"]
  use_cpu: false

lora_config:
  r: 32
  lora_alpha: 64
  target_modules: ["c_attn", "c_proj"]
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"
  fan_in_fan_out: true